### ISSUE TITLE
Error: Plugin could not be registered at 'html-webpack-plugin-alter-asset-tags'. Hook was not found.

### ISSUE THREAD

**Issue by tzs007** [webpack/tapable#111]
Hello,

Unfortunately, I cannot build my react project because of this error. I'm puzzled, because it's a dependency of webpack, so I can't change or fixed that error.

I tried with 8.16.0 and 10.16.0 node, reinstalled node_modules with yarn an npm, but I got same error.

It's so urgent, because I must hand the project over to my client in this week.

Thank you!

```
tzs007@MSI:~/_localhost/tennissignal$ npm run build

> mouldifi-bs4-react@1.3.0 build /home/tzs007/_localhost/tennissignal
> webpack --progress --bail --env dist -p

/home/tzs007/_localhost/tennissignal/node_modules/tapable/lib/Tapable.js:69
                throw new Error(
                ^

Error: Plugin could not be registered at 'html-webpack-plugin-alter-asset-tags'. Hook was not found.
BREAKING CHANGE: There need to exist a hook at 'this.hooks'. To create a compatibility layer for this hook, hook into 'this._pluginCompat'.
    at Compilation.plugin (/home/tzs007/_localhost/tennissignal/node_modules/tapable/lib/Tapable.js:69:9)
    at Compilation.deprecated [as plugin] (internal/util.js:66:15)
    at compiler.plugin (/home/tzs007/_localhost/tennissignal/node_modules/script-ext-html-webpack-plugin/lib/plugin.js:37:19)
    at SyncHook.eval [as call] (eval at create (/home/tzs007/_localhost/tennissignal/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:17:1)
    at SyncHook.lazyCompileHook (/home/tzs007/_localhost/tennissignal/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/home/tzs007/_localhost/tennissignal/node_modules/webpack/lib/Compiler.js:631:26)
    at hooks.beforeCompile.callAsync.err (/home/tzs007/_localhost/tennissignal/node_modules/webpack/lib/Compiler.js:667:29)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/tzs007/_localhost/tennissignal/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/tzs007/_localhost/tennissignal/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/home/tzs007/_localhost/tennissignal/node_modules/webpack/lib/Compiler.js:662:28)
    at readRecords.err (/home/tzs007/_localhost/tennissignal/node_modules/webpack/lib/Compiler.js:321:11)
    at Compiler.readRecords (/home/tzs007/_localhost/tennissignal/node_modules/webpack/lib/Compiler.js:529:11)
    at hooks.run.callAsync.err (/home/tzs007/_localhost/tennissignal/node_modules/webpack/lib/Compiler.js:318:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/tzs007/_localhost/tennissignal/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/tzs007/_localhost/tennissignal/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.beforeRun.callAsync.err (/home/tzs007/_localhost/tennissignal/node_modules/webpack/lib/Compiler.js:315:19)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/tzs007/_localhost/tennissignal/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/home/tzs007/_localhost/tennissignal/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.run (/home/tzs007/_localhost/tennissignal/node_modules/webpack/lib/Compiler.js:312:24)
    at processOptions (/home/tzs007/_localhost/tennissignal/node_modules/webpack-cli/bin/cli.js:353:14)
    at yargs.parse (/home/tzs007/_localhost/tennissignal/node_modules/webpack-cli/bin/cli.js:364:3)
    at Object.parse (/home/tzs007/_localhost/tennissignal/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /home/tzs007/_localhost/tennissignal/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/home/tzs007/_localhost/tennissignal/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/tzs007/_localhost/tennissignal/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mouldifi-bs4-react@1.3.0 build: `webpack --progress --bail --env dist -p`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mouldifi-bs4-react@1.3.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tzs007/.npm/_logs/2019-10-27T23_59_07_654Z-debug.log
```

**Comment by evilebottnawi** [comment]
Please report issue in `html-webpack-plugin-alter-asset-tags`, thanks

**Comment by MarcusWolschon** [comment]
So is there an issue in that other project yet?
Could anyone link it here for people to navigate to the correct ticket?

**Comment by Hongbo-Miao** [comment]
Hmm, got same error, and cannot find a solution...

```
/my-project/node_modules/tapable/lib/Tapable.js:69
		throw new Error(
		^

Error: Plugin could not be registered at 'html-webpack-plugin-alter-asset-tags'. Hook was not found.
BREAKING CHANGE: There need to exist a hook at 'this.hooks'. To create a compatibility layer for this hook, hook into 'this._pluginCompat'.
    at Compilation.plugin (/my-project/node_modules/tapable/lib/Tapable.js:69:9)
    at Compilation.deprecated [as plugin] (internal/util.js:89:15)
    at /my-project/node_modules/html-webpack-inline-chunk-plugin/index.js:18:21
    at SyncHook.eval (eval at create (/my-project/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:5:1)
    at SyncHook.lazyCompileHook (/my-project/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/my-project/node_modules/webpack/lib/Compiler.js:631:26)
    at /my-project/node_modules/webpack/lib/Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/my-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/my-project/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/my-project/node_modules/webpack/lib/Compiler.js:662:28)
```

**Comment by Hongbo-Miao** [comment]
Got same error, there two might help future people.

- https://github.com/jantimon/html-webpack-plugin/issues/875
- https://github.com/webpack/webpack/issues/6481

In my case, it was caused by an old plugin `html-webpack-inline-chunk-plugin` which does not support Webpack 4. Once removing it, the error is gone.
