### ISSUE TITLE
Not compatible with webpack v5

### ISSUE THREAD

**Issue by ayxos** [webpack/tapable#145]
Looks like a problem with deprecated hooks
```
[webpack-cli] Uncaught exception: Error: NormalModuleFactory.afterResolve is no longer a waterfall hook, but a bailing hook instead. Do not return the passed object, but modify it instead. Returning false will ignore the request and results in no module created.
[webpack-cli] Error: NormalModuleFactory.afterResolve is no longer a waterfall hook, but a bailing hook instead. Do not return the passed object, but modify it instead. Returning false will ignore the request and results in no module created.
    at /app/node_modules/webpack/lib/NormalModuleFactory.js:251:14
    at Hook.eval [as callAsync] (eval at create (/app/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/app/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at /app/node_modules/webpack/lib/NormalModuleFactory.js:247:30
    at eval (eval at create (/app/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /app/node_modules/webpack/lib/NormalModuleFactory.js:481:7
    at /app/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /app/node_modules/webpack/lib/NormalModuleFactory.js:513:8
    at NormalModuleFactory.resolveRequestArray (/app/node_modules/webpack/lib/NormalModuleFactory.js:734:34)
    at /app/node_modules/webpack/lib/NormalModuleFactory.js:505:11
```

**Comment by evilebottnawi** [comment]
No, please read the error message, maybe some plugin(s) use old API, you need to open an issue in plugin, but you don't provide more information, so I can'y help, sorry

If you want to found the problem please create reproducible test repo, stack trace don't help
