### ISSUE TITLE
Error using interception API with SyncBailHook

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/tapable#42]
Here is a simple configuration I had while linked up to webpack#next

**webpack.config.js**

```javascript
const path = require('path');
const webpack = require('webpack');

module.exports = {
    entry: './src',
    output: {
        path: path.join(__dirname, 'dist'),
        filename: 'chunk.js'
    },
    plugins: [
        new webpack.ProgressPlugin(),
        function () {
            const compiler = this;

            Object.keys(compiler.hooks).forEach((hookName) => {
                compiler.hooks[hookName].intercept(interceptorFor(hookName));
            });
        }
    ]
};

const interceptorFor = (hookName) => ({
    call: (...args) => {
        console.log(`Intercepting Call: ${hookName}\n Args: ${JSON.stringify([...args])}`);
    },
    tap: (tapDetails) => {
        console.log(`Intercepting Tap: ${JSON.stringify(tapDetails)}`);
    } 
});
```

This is the error that threw:

**console output**

```
TypeError: Cannot read property 'fn' of undefined
    at SyncBailHook.eval [as call] (eval at compile (/mnt/c/Users/selarkin/Code/webpack/node_modules/tapable/lib/Hook.js:21:10), <anonymous>:12:28)
    at SyncBailHook.eval [as _call] (eval at createCompileDelegate (/mnt/c/Users/selarkin/Code/webpack/node_modules/tapable/lib/Hook.js:55:10), <anonymous>:5:16)
    at WebpackOptionsApply.process (/mnt/c/Users/selarkin/Code/webpack/lib/WebpackOptionsApply.js:264:30)
    at webpack (/mnt/c/Users/selarkin/Code/webpack/lib/webpack.js:35:48)
    at processOptions (/mnt/c/Users/selarkin/Code/webpack/bin/webpack.js:357:15)
    at yargs.parse (/mnt/c/Users/selarkin/Code/webpack/bin/webpack.js:418:2)
    at Object.Yargs.self.parse (/mnt/c/Users/selarkin/Code/webpack/node_modules/yargs/yargs.js:533:18)
    at Object.<anonymous> (/mnt/c/Users/selarkin/Code/webpack/bin/webpack.js:154:7)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by TheLarkInn** [comment]
If I am not using the api correctly, let me know. Was trying to grab all hooks and intercept them.

**Comment by TheLarkInn** [comment]
For contributors wanting to sniff this out: 

The problem lies within this block of code: 

https://github.com/webpack/tapable/blob/dbdefddb20a654e1b265577b253c23bbb5578e49/lib/SyncBailHook.js#L59-L73

Either simple logic, or var scoping maybe? Steps should be reproducible even with a simple interceptor for `compiler.hooks.entryOption`

**Comment by Itrulia** [comment]
Didn't had time yet to actually run it through, but I might have found the issue.

```
_tap = _intercept[_j].tap(_tap); 
const _result = _tap.fn(${args}); 
```

here you expect that `_intercept[_j].tap(_tap); ` returns an object with a method property of `fn(args) => any`, but the function you declared returned nothing.


```
const interceptorFor = (hookName) => ({
    ...
    tap: (tapDetails) => {
        console.log(`Intercepting Tap: ${JSON.stringify(tapDetails)}`);

        // tap returns nothing here, which results in the error `Cannot read property 'fn' of undefined`
    } 
});
```


If you can confirm it's not that, I will look in to it if I ever get time :)

**Comment by TheLarkInn** [comment]
Totally didn't even realize that!! I'll give it a quick spin when I have a chance later and try it!!!!

**Comment by sokra** [comment]
It should be:

``` js
    tap: (tapDetails) => {
        console.log(`Intercepting Tap: ${JSON.stringify(tapDetails)}`);
        return tapDetails;
    }
```

**Comment by Itrulia** [comment]
Ha, that's why I love pair programming :) sometimes you can't see the forrest because of all the trees.

**Comment by TheLarkInn** [comment]
Just figured that out stepping through it.

@sokra is this needing to return because it's bailing or not?

**Comment by TheLarkInn** [comment]
Alright I understand the context now. I'm going to PR the readme where it was unclear to me and make it explicit. 

If it could happen to me hopefully I won't be the last.

**Comment by TheLarkInn** [comment]
Closing as was a difference in understanding on my part. Updated docs in merge.
