### ISSUE TITLE
Error: Cannot find module 'upath'

### ISSUE THREAD

**Issue by geminiyellow** [webpack/tapable#59]
when i upgrade my node version to `10.0.0`, boom ↓ 

any idea?

**ENV**

```
$ node -v
v10.0.0
$ npm -v
6.0.0
```

**DETAIL**

```
10:46:33 webpack.1   | Error: Cannot find module 'upath'
10:46:33 webpack.1   |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
10:46:33 webpack.1   |     at Function.Module._load (internal/modules/cjs/loader.js:497:25)
10:46:33 webpack.1   |     at Module.require (internal/modules/cjs/loader.js:626:17)
10:46:33 webpack.1   |     at require (/Users/developer/Documents/Sources/server/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
10:46:33 webpack.1   |     at Object.<anonymous> (/Users/developer/Documents/Sources/server/node_modules/chokidar/index.js:13:13)
10:46:33 webpack.1   |     at Module._compile (/Users/developer/Documents/Sources/server/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
10:46:33 webpack.1   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
10:46:33 webpack.1   |     at Module.load (internal/modules/cjs/loader.js:589:32)
10:46:33 webpack.1   |     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
10:46:33 webpack.1   |     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
10:46:33 webpack.1   |     at Module.require (internal/modules/cjs/loader.js:626:17)
10:46:33 webpack.1   |     at require (/Users/developer/Documents/Sources/server/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
10:46:33 webpack.1   |     at Object.<anonymous> (/Users/developer/Documents/Sources/server/node_modules/watchpack/lib/DirectoryWatcher.js:9:16)
10:46:33 webpack.1   |     at Module._compile (/Users/developer/Documents/Sources/server/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
10:46:33 webpack.1   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
10:46:33 webpack.1   |     at Module.load (internal/modules/cjs/loader.js:589:32)
10:46:33 webpack.1   |     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
10:46:33 webpack.1   |     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
10:46:33 webpack.1   |     at Module.require (internal/modules/cjs/loader.js:626:17)
10:46:33 webpack.1   |     at require (/Users/developer/Documents/Sources/server/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
10:46:33 webpack.1   |     at WatcherManager.getDirectoryWatcher (/Users/developer/Documents/Sources/server/node_modules/watchpack/lib/watcherManager.js:14:25)
10:46:33 webpack.1   |     at WatcherManager.watchFile (/Users/developer/Documents/Sources/server/node_modules/watchpack/lib/watcherManager.js:28:14)
10:46:33 webpack.1   |     at Watchpack.<anonymous> (/Users/developer/Documents/Sources/server/node_modules/watchpack/lib/watchpack.js:38:49)
10:46:33 webpack.1   |     at Array.map (<anonymous>)
10:46:33 webpack.1   |     at Watchpack.watch (/Users/developer/Documents/Sources/server/node_modules/watchpack/lib/watchpack.js:37:28)
10:46:33 webpack.1   |     at NodeWatchFileSystem.watch (/Users/developer/Documents/Sources/server/node_modules/webpack/lib/node/NodeWatchFileSystem.js:53:16)
10:46:33 webpack.1   |     at Watching.watch (/Users/developer/Documents/Sources/server/node_modules/webpack/lib/Watching.js:115:48)
10:46:33 webpack.1   |     at compiler.hooks.done.callAsync (/Users/developer/Documents/Sources/server/node_modules/webpack/lib/Watching.js:102:10)
10:46:33 webpack.1   |     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/developer/Documents/Sources/server/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
10:46:33 webpack.1   |     at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/developer/Documents/Sources/server/node_modules/tapable/lib/Hook.js:35:21)
10:46:33 webpack.1   | npm ERR! code ELIFECYCLE
10:46:33 webpack.1   | npm ERR! errno 1
```

**Comment by shsssskn** [comment]
@geminiyellow 

maybe https://github.com/airbnb/enzyme/issues/1637#issuecomment-397327562

**Comment by sokra** [comment]
Not related to this library

**Comment by haihuo0910** [comment]
你怎么解决的？

**Comment by haihuo0910** [comment]
我也遇到同样的问题了
